appFive/urls.py
from django.urls import path, re_path
from appFive import views

app_name = 'appFive'
urlpatterns = [
    re_path(r'^register/$',views.register, name='register'),
    re_path(r'^user_login/$',views.user_login, name='user_login'),
]

first_task5/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from appFive import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^appFive', include('appFive.urls')),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^logout/$', views.user_logout, name='logout'),
    re_path(r'^special/', views.special, name='special'),
]

appFive/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE)
   name = models.CharField(max_length=255, default='')
   portfolio_site = models.URLField(blank=True)
   profile_pic = models.ImageField(upload_to='profile_pic', blank=True)
   def __str__(self):
      return self.user.username 

appFive/forms.py
from django import forms
from django.contrib.auth.models import User
from appFive.models import UserProfileInfo  # Import your User model


# class NewUserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = '__all__'
# class FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     text = forms.CharField(widget=forms.Textarea)
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
# class UserSignUpForm(forms.Form):
#     class Meta:
#         model = User 
#         fields = ['username','email', 'password']
#         widgets =  {
#             'password':forms.PasswordInput(),
#         }

# class YourFormName(forms.ModelForm):
#     class Meta:
#         model = YourModel  # Replace 'YourModel' with your actual model name
#         fields = ['username','email', 'password']
#         widgets =  {
#             'password':forms.PasswordInput(),
#         }

appFive/views.py
from django.shortcuts import render
from appFive.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'appFive/index.html')
@login_required
def special(request):
    return HttpResponse('You are logged in!')
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
            messages.success(request, "Đăng ký thành công!")  # Thêm thông báo thành công

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'appFive/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})
    
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('Someone tried to login and fail!')
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'appFive/login.html',{})

templates/appFive/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>appFive</title>
</head>
<body>
    <h1>welcome to relative URL template</h1>
    <ul>
        <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a> </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'appFive:register' %}">Register</a> </li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a> </li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'appFive:user_login' %}">Login</a> </li>
        {% endif %}
    </ul>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/appFive/index.html
{% extends "appFive/base.html" %}
{% block body_block %}
<h1>
    This is home page
</h1>
<div class="mt-4 p-5 bg-light rounded">
    <h1>This is en example of template inheritance!</h1>
</div>
{% endblock %}

templates/appFive/login.html
{% extends "appFive/base.html" %}
{% block body_block %}
<h1>
    This is home page
</h1>
<div class="mt-4 p-5 bg-light rounded">
    <h1>Please Login</h1>
    <form action="{% url 'appFive:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username"> Username: </label>
        <input type="text" name="username">

        <label for="password"> Password: </label>
        <input type="password" name="password">
        <input type="submit" value="Login" class="btn btn-success">
    </form>
</div>
{% endblock %}

templates/appFive/registration.html
{% extends "appFive/base.html" %}
{% load static %}
{% block body_block %}

<div class="mt-4 p-5 bg-light rounded">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form!</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register" class="btn btn-info">
    </form>
    {% endif %}
    
</div>
{% endblock %}

templates/appFour/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Fisrt App</title>
</head>
<body>
    <h1>welcome to relative URL template</h1>
    <ul>
        <li><a href="{% url "index" %}">Home</a> </li>
        <li><a href="{% url "appFour:page1" %}">page1</a> </li>
        <li><a href="{% url "appFour:page2" %}">page2</a> </li>
    </ul>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/appFour/index.html
{% extends "appFour/base.html" %}
{% block body_block %}
<h1>
    This is home page
</h1>
<h1>
    This is en example of template inheritance!
</h1>
{{ text | cut:"Hello"}}
{{ number | cut:"99"}}
{% endblock %}

templates/appFour/page1.html
{% extends "appFour/base.html" %}
{% block body_block %}
<h1>
    This is home page1
</h1>
{% endblock %}

templates/appFour/page2.html
{% extends "appFour/base.html" %}
{% block body_block %}
<h1>
    This is home page2
</h1>
{% endblock %}

templates/basic_app/form.html
<!DOCTYPE html>
{% csrf_token %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>FORM</title>
</head>
<body>
    <h1>Fill out the form </h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>HOME</title>
</head>
<body>
    <h1>Welcome to home page!</h1>
    <H2>Go to /forpage to fill out the from </H2> 
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Fisrt App</title>
</head>
<body>
    <h1>Hello this is templates/index.html</h1>
    {% if access_records %}
    
    <table>
        <thead>
            <th>Site Name </th>
            <th>Date Accessed</th>
        </thead>
        {% for record in access_records %}
        <tr>
            <td>{{ record.name }}</td>
            <td>{{ record.date }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>NO ACCESS RECORDS FOUND!</p>
    {% endif %}    
</body>
</html>

templates/user/user.html
<!DOCTYPE html>
{% csrf_token %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>FORM</title>
</head>
<body>
    <h1>Fill out the form </h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Đăng ký</button>
    </form>
</body>
</html>